version: '3.4'

volumes:
  django_sample.db.volume:
    name: django_sample.db.volume
  django_sample.postgres-data:
    name: django_sample.postgres-data
  staticdata:

services:
  mysql:
    image: mysql:5.7
    container_name: django_sample.db
    environment:
      MYSQL_ROOT_PASSWORD: x7guCQ3AELNu
      MYSQL_USER: web
      MYSQL_PASSWORD: x7guCQ3AELNu
      MYSQL_DATABASE: web
    volumes:
      - django_sample.db.volume:/var/lib/mysql
    ports:
      - 3306:3306
    tty: true
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx
    ports:
      - "5432:5432"
    container_name: django_sample.postgres-db
    volumes:
      - django_sample.postgres-data:/var/lib/postgresql/data
  web:
    container_name: django_sample.web
    restart: always
    build: ./web/
    expose:
      - "8001"
    command: gunicorn django_sample.wsgi -b 0.0.0.0:8001
    # command: python manage.py runserver 0.0.0.0:8001
    # ports:
    #   - "8001:8001"
    volumes:
      - "staticdata:/usr/src/django_sample/static/"
    depends_on:
      - mysql
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - "staticdata:/usr/src/django_sample/static/"
    depends_on:
      - web
